direction: right

vars {
    DutServ: Dut Serv
}

classes {
    ConnLabel: {
        style: {
            font-size: 20
            font-color: black
        }
    }

    ConnLine: {
        style: {
            font-color: purple
            stroke: red
        }
    }
}

SST: SST Slot {
    # near: top-left
    
    # grid-rows: 2
    grid-columns: 2

    PDB: "PDB" {
        # grid-rows: 2
        grid-columns: 2

        SBC1: SBC {
            DutServ: ${DutServ}
        }
        SBC2: SBC {
            DutServ: ${DutServ}
        }
        SBC3: SBC{
            DutServ: ${DutServ}
        }
        SBC4: SBC{
            DutServ: ${DutServ}
        }
    }

    TIB: "TIB" {
        # grid-rows: 2
        grid-columns: 2

        DUT1: DUT
        DUT2: DUT
        DUT3: DUT
        DUT4: DUT
        DUT5: DUT
        DUT6: DUT
        DUT7: DUT
        DUT8: DUT
    }   
}

WS: Windows Workstation  {
    # near: bottom-left
    ActivATE
}

LS: Linux Workstation {
    # direction: up
    # near: bottom-right
    ASV
    ST8: SmartTest8    
}

Moonraker: {
    near: top-right
    COM
}

SST.TIB.DUT8 <- SST.PDB.SBC4.DutServ <- WS.ActivATE : normal test { class: ConnLabel }
LS.ASV <- WS.ActivATE: Http Request { class: [ConnLabel; ConnLine] }
SST.TIB.DUT8 <- Moonraker.COM <- LS.ST8 <- LS.ASV: debug test { class: [ConnLabel; ConnLine] }
