direction: right

vars {
    DutServ: Dut Serv {
        shape: image
        icon: https://icons.terrastruct.com/tech%2F069-hard-drive.svg
    }

    Dut: {
        icon: https://icons.terrastruct.com/aws%2FInternet%20of%20Things%2FIoT_Alexa-enabled-device_light-bg.svg
    }
}

classes {
    ConnLabel: {
        style: {
            font-size: 20
            font-color: black
        }
    }

    ConnLine: {
        style: {
            font-color: purple
            stroke: red
        }
    }
}

User1: Unified SLT/ABI User {
    style: {
        font-size: 24
        font-color: black
    }
    near: top-left
    shape: person
}

SLT: ActivATE Workstation  {
    # near: bottom-left
    ActivATE {
        icon: https://icons.terrastruct.com/tech%2Fdesktop.svg
    }
}

DDB: SLT Developer Debug Board {
    # near: top-right
    # grid-rows: 2

    SBC: SBC/COM {
        DutServ: ${DutServ}
    }

    DUTs: "" {
        grid-rows: 1
        DUT1: ${Dut}
        DUT2: ${Dut}
        DUT3: ${Dut}
        DUT4: ${Dut}
    }
}

User1 -> SLT: SLT Test && Debug Test { class: ConnLabel }
SLT -> DDB.SBC.DutServ -> DDB.DUTs.DUT4: SLT Test { class: ConnLabel}

DS: ST8 Debug Solution {
    # near: bottom-right
    # grid-rows: 2
    
    # DutServ: ${DutServ}
    
    ST: "" {
        shape: image
        icon: https://icons.terrastruct.com/tech/022-server.svg
        width: 250
        height: 250
    }
}

# SLT -> DS.DutServ: Debug Test  { class: [ConnLabel; ConnLine]}
SLT -> DS.ST -> DDB.DUTs.DUT4: Debug Test { class: [ConnLabel; ConnLine]}
