# direction: down

vars {
    DutServ: Dut Serv
}

classes {
    ConnLable: {
        style: {
            font-size: 20
            font-color: black
        }
    }
}

SST {
    # near: top-left
    
    label: "SST Slot"
    grid-rows: 2

    PDB: "PDB" {
        grid-rows: 2

        SBC1: SBC {
            DutServ: ${DutServ}
        }
        SBC2: SBC {
            DutServ: ${DutServ}
        }
        SBC3: SBC{
            DutServ: ${DutServ}
        }
        SBC4: SBC{
            DutServ: ${DutServ}
        }
    }

    TIB: "TIB" {
        grid-rows: 2

        DUT1: DUT
        DUT2: DUT
        DUT3: DUT
        DUT4: DUT
        DUT5: DUT
        DUT6: DUT
        DUT7: DUT
        DUT8: DUT
    }   
}

WS: Windows Workstation  {
    # near: top-right
    ActivATE
}

Moonraker: {
    DutServ: ${DutServ}
    COM
}

SST.TIB.DUT8 <- SST.PDB.SBC4.DutServ <- WS.ActivATE : normal test { class: ConnLable }
SST.TIB.DUT8 <- Moonraker.COM <- Moonraker.DutServ <- WS.ActivATE : debug test { class: ConnLable }
