direction: right

vars {
    DutServ: Dut Serv {
        shape: image
        icon: https://icons.terrastruct.com/tech%2F069-hard-drive.svg
    }

    Dut: {
        icon: https://icons.terrastruct.com/aws%2FInternet%20of%20Things%2FIoT_Alexa-enabled-device_light-bg.svg
    }
}

classes {
    ConnLabel: {
        style: {
            font-size: 20
            font-color: black
        }
    }

    ConnLine: {
        style: {
            font-color: purple
            stroke: red
        }
    }
}

User1: User {
    # near: top-right
    shape: person
}

SLT: ActivATE Workstation  {
    ActivATE {
        icon: https://icons.terrastruct.com/tech%2Fdesktop.svg
    }
}

User1 -> SLT -> PSV.DutServ -> PSV.QC -> QC: Debug Test { class: ConnLabel}


PSV: ASV Box {
    # near: top-right
    
    shape: hexagon
    # icon: https://icons.terrastruct.com/infra%2F002-backup.svg

    DutServ: Device360 ("dut-svr") {
        shape: image
        icon: https://icons.terrastruct.com/tech%2Fbrowser-2.svg
    }

    QC: Customer Binaries {
        shape: image
        icon: https://icons.terrastruct.com/tech%2F014-cpu.svg
    }
}

QC: Customer Board {
    shape: image
    icon: https://icons.terrastruct.com/tech%2F012-cpu-2.svg
}

