direction: right

vars {
    DutServ: Dut Serv {
        shape: image
        width: 24
        height: 20
        icon: https://icons.terrastruct.com/tech%2F069-hard-drive.svg
    }

    Dut: {
        icon: https://icons.terrastruct.com/aws%2FInternet%20of%20Things%2FIoT_Alexa-enabled-device_light-bg.svg
    }
}

classes {
    ConnLabel: {
        style: {
            font-size: 20
            font-color: black
        }
    }

    ConnLine: {
        style: {
            font-color: purple
            stroke: red
        }
    }
}

SST: SST Slot {   
    # near: top-left
    # grid-rows: 2
    grid-columns: 2

    PDB: "PDB" {
        # grid-rows: 2
        grid-columns: 4

        SBC1: "" {
            DutServ: ${DutServ}
        }
        SBC2: "" {
            DutServ: ${DutServ}
        }
        SBC3: ""{
            DutServ: ${DutServ}
        }
        SBC4: "" {
            DutServ: ${DutServ}
        }
        SBC5: "" {
            DutServ: ${DutServ}
        }
        SBC6: "" {
            DutServ: ${DutServ}
        }
        SBC7: "" {
            DutServ: ${DutServ}
        }
        SBC8: "" {
            DutServ: ${DutServ}
        }
        SBC9: "" {
            DutServ: ${DutServ}
        }
        SBC10: "" {
            DutServ: ${DutServ}
        }
        SBC11: "" {
            DutServ: ${DutServ}
        }
        SBC12: "" {
            DutServ: ${DutServ}
        }
        SBC13: "" {
            DutServ: ${DutServ}
        }
        SBC14: "" {
            DutServ: ${DutServ}
        }
        SBC15: "" {
            DutServ: ${DutServ}
        }
        SBC16: "" {
            DutServ: ${DutServ}
        }
        SBC17: "" {
            DutServ: ${DutServ}
        }
        SBC18: "" {
            DutServ: ${DutServ}
        }
        SBC19: "" {
            DutServ: ${DutServ}
        }
        SBC20: "" {
            DutServ: ${DutServ}
        }
        SBC21: "" {
            DutServ: ${DutServ}
        }
        SBC22: "" {
            DutServ: ${DutServ}
        }
        SBC23: "" {
            DutServ: ${DutServ}
        }
        SBC24: "" {
            DutServ: ${DutServ}
        }
    }

    TIB: "TIB" {
        # grid-rows: 2
        grid-columns: 4

        DUT1: ${DUT}
        DUT2: ${DUT}
        DUT3: ${DUT}
        DUT4: ${DUT}
        DUT5: ${DUT}
        DUT6: ${DUT}
        DUT7: ${DUT}
        DUT8: ${DUT}
        DUT9: ${DUT}
        DUT9: ${DUT}
        DUT10: ${DUT}
        DUT11: ${DUT}
        DUT12: ${DUT}
        DUT13: ${DUT}
        DUT14: ${DUT}
        DUT15: ${DUT}
        DUT16: ${DUT}
        DUT17: ${DUT}
        DUT18: ${DUT}
        DUT19: ${DUT}
        DUT20: ${DUT}
        DUT21: ${DUT}
        DUT22: ${DUT}
        DUT23: ${DUT}
        DUT24: ${DUT}
    }   
}

WS: ActivATE Workstation  {
    # near: bottom-left
    ActivATE {
        icon: https://icons.terrastruct.com/tech%2Fdesktop.svg
    }
}

DS: ST8 Debug Solution {
    # near: bottom-right
    # grid-rows: 2

    ST: "" {
        shape: image
        icon: https://icons.terrastruct.com/tech/022-server.svg
        width: 300
        height: 300
    }

    DutServ: Dut Serv {
        shape: image
        icon: https://icons.terrastruct.com/tech%2F069-hard-drive.svg
    }
}

SST.TIB.DUT24 <- SST.PDB.SBC24.DutServ <- WS.ActivATE : normal test { class: ConnLabel }
SST.TIB.DUT24 <- DS.ST <- DS.DutServ <- WS.ActivATE: Debug Test { class: [ConnLabel; ConnLine] }

